{ pkgs, nasMount, ... }: {
  networking.hostName = "vm-108";

  fileSystems = nasMount "/var/lib/forgejo-runner" "forgejo-runner"
    // nasMount "/var/lib/homepage-tokens" "homepage-tokens";

  virtualisation.docker.enable = true;

  virtualisation.oci-containers.backend = "docker";
  virtualisation.oci-containers.containers.forgejo-runner = {
    image = "code.forgejo.org/forgejo/runner:6.2.1";
    cmd = [ "forgejo-runner" "daemon" "--config" "/data/config.yaml" ];
    volumes = [
      "/var/lib/forgejo-runner:/data"
      "/var/run/docker.sock:/var/run/docker.sock"
    ];
    user = "root:root";
    extraOptions = [
      "--add-host=git.lsck0.dev:10.100.0.100"
      "--add-host=registry.lsck0.dev:10.100.0.109"
      "--add-host=sccache.lsck0.dev:10.100.0.106"
    ];
    environment = {
      SCCACHE_REDIS = "redis://sccache.lsck0.dev";
    };
  };

  # Register runner with Forgejo using token from NAS (generated by VM 107)
  systemd.services.forgejo-runner-register = {
    description = "Register Forgejo runner";
    before = [ "docker-forgejo-runner.service" ];
    requiredBy = [ "docker-forgejo-runner.service" ];
    path = [ pkgs.curl pkgs.jq pkgs.docker pkgs.gnused ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      # Skip if already registered
      if [ -f /var/lib/forgejo-runner/.runner ]; then
        echo "Runner already registered"
        exit 0
      fi

      # Generate default config if missing
      if [ ! -f /var/lib/forgejo-runner/config.yaml ]; then
        docker run --rm -v /var/lib/forgejo-runner:/data \
          code.forgejo.org/forgejo/runner:6.2.1 \
          forgejo-runner generate-config > /var/lib/forgejo-runner/config.yaml
      fi

      # Wait for Forgejo API
      for i in $(seq 1 90); do
        if curl -sf https://git.lsck0.dev/api/v1/settings/api >/dev/null 2>&1; then break; fi
        sleep 2
      done

      # Read registration token from NAS (generated by Forgejo VM)
      TOKEN_FILE="/var/lib/homepage-tokens/forgejo-runner.token"
      for i in $(seq 1 30); do
        [ -f "$TOKEN_FILE" ] && [ -s "$TOKEN_FILE" ] && break
        sleep 5
      done

      if [ ! -f "$TOKEN_FILE" ] || [ ! -s "$TOKEN_FILE" ]; then
        echo "ERROR: Runner token not found at $TOKEN_FILE"
        echo "Ensure Forgejo VM (107) is deployed and running."
        exit 1
      fi

      REG_TOKEN=$(cat "$TOKEN_FILE")

      docker run --rm -v /var/lib/forgejo-runner:/data \
        --add-host=git.lsck0.dev:10.100.0.100 \
        code.forgejo.org/forgejo/runner:6.2.1 \
        forgejo-runner register \
          --instance https://git.lsck0.dev \
          --token "$REG_TOKEN" \
          --name vm-108-runner \
          --labels "docker:docker://node:20-bookworm,ubuntu-latest:docker://catthehacker/ubuntu:act-22.04,rust:docker://rust:1.80-bookworm" \
          --no-interactive

      echo "Runner registered successfully"
    '';
  };

  systemd.tmpfiles.rules = [
    "d /var/lib/forgejo-runner 0750 1000 1000 -"
  ];

  networking.firewall.allowedTCPPorts = [];
}
