{ pkgs, nasMount, retry, ... }: {
  networking.hostName = "vm-116";

  fileSystems = nasMount "/var/lib/forgejo-runner" "forgejo-runner"
    // nasMount "/var/lib/homepage-tokens" "homepage-tokens";

  virtualisation.docker.enable = true;

  virtualisation.oci-containers.backend = "docker";
  virtualisation.oci-containers.containers.forgejo-runner = {
    image = "code.forgejo.org/forgejo/runner:6.2.1";
    cmd = [ "forgejo-runner" "daemon" "--config" "/data/config.yaml" ];
    volumes = [
      "/var/lib/forgejo-runner:/data"
      "/var/run/docker.sock:/var/run/docker.sock"
    ];
    user = "root:root";
    extraOptions = [
      "--add-host=git.lsck0.dev:10.100.0.100"
      "--add-host=registry.lsck0.dev:10.100.0.118"
      "--add-host=sccache.lsck0.dev:10.100.0.111"
    ];
    environment = {
      SCCACHE_REDIS = "redis://sccache.lsck0.dev";
    };
  };

  # register runner with Forgejo using token from NAS (generated by VM 107)
  systemd.services.forgejo-runner-register = {
    description = "Register Forgejo runner";
    before = [ "docker-forgejo-runner.service" ];
    requiredBy = [ "docker-forgejo-runner.service" ];
    path = [ pkgs.curl pkgs.jq pkgs.docker pkgs.gnused ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      # generate default config if missing
      if [ ! -f /var/lib/forgejo-runner/config.yaml ]; then
        docker run --rm -v /var/lib/forgejo-runner:/data \
          code.forgejo.org/forgejo/runner:6.2.1 \
          forgejo-runner generate-config > /var/lib/forgejo-runner/config.yaml
      fi

      # patch config: mount Docker socket in job containers (needed for docker build/push in CI)
      sed -i 's|docker_host: "-"|docker_host: "automount"|' /var/lib/forgejo-runner/config.yaml
      # ensure job containers can resolve internal hostnames (match exact key under container section)
      sed -i '/^container:/,/^[^ ]/{s|^  options: .*|  options: "--add-host=git.lsck0.dev:10.100.0.100 --add-host=registry.lsck0.dev:10.100.0.118 --add-host=sccache.lsck0.dev:10.100.0.111"|}' \
        /var/lib/forgejo-runner/config.yaml

      # wait for Forgejo API
      ${retry} 90 2 curl -sf https://git.lsck0.dev/api/healthz

      # validate existing registration by pinging Forgejo with runner credentials.
      # if ping fails the token is stale (e.g. after a Forgejo DB reset), re-register.
      if [ -f /var/lib/forgejo-runner/.runner ]; then
        if docker run --rm \
          -v /var/lib/forgejo-runner:/data \
          --add-host=git.lsck0.dev:10.100.0.100 \
          code.forgejo.org/forgejo/runner:6.2.1 \
          forgejo-runner ping --instance https://git.lsck0.dev >/dev/null 2>&1; then
          echo "Runner already registered and valid"
          exit 0
        fi
        echo "Runner ping failed: token likely stale, re-registering..."
        rm -f /var/lib/forgejo-runner/.runner
      fi

      # read registration token from NAS (generated by Forgejo VM)
      TOKEN_FILE="/var/lib/homepage-tokens/forgejo-runner.token"
      ${retry} 30 5 test -s "$TOKEN_FILE" || { echo "runner token missing at $TOKEN_FILE: is vm-115 (Forgejo) up?"; exit 1; }

      REG_TOKEN=$(cat "$TOKEN_FILE")

      # `docker` must map to an image that HAS the docker CLI. It was
      # node:20-bookworm, which does not, so every workflow using
      # `runs-on: docker` to build an image died on "docker: command not found"
      # five seconds in - the hello pipeline had never once worked. The
      # catthehacker image carries docker and node both, and node is needed
      # because actions/checkout is a JS action.
      docker run --rm -v /var/lib/forgejo-runner:/data \
        --add-host=git.lsck0.dev:10.100.0.100 \
        code.forgejo.org/forgejo/runner:6.2.1 \
        forgejo-runner register \
          --instance https://git.lsck0.dev \
          --token "$REG_TOKEN" \
          --name vm-116-runner \
          --labels "docker:docker://catthehacker/ubuntu:act-22.04,ubuntu-latest:docker://catthehacker/ubuntu:act-22.04,rust:docker://rust:1.80-bookworm" \
          --no-interactive

      echo "Runner registered successfully"
    '';
  };

  systemd.tmpfiles.rules = [
    "d /var/lib/forgejo-runner 0750 1000 1000 -"
  ];

  networking.firewall.allowedTCPPorts = [];
}
