#!/usr/bin/env bash
# converge the repo's sops files to the lab's secrets layout (modules/secrets.nix)
#
# The layout's plan says which file holds each declared secret and which hosts read each file. This script makes the
# files say the same:
#   - every host has a key in its home folder: age.pub, and age.sops (the private key, admins only)
#   - .sops.yaml has one creation rule per file: the admins of src/secrets/admins.txt plus the file's readers
#   - every declared secret has a value in its file: a missing one is generated by its kind (src/secrets/shared.nix), or
#     added empty for a human; one found in another file moves there. --prune deletes undeclared ones. A missing
#     guardsData secret stops the run unless --generate-guarded says it is new
#   - every host reading shared secrets gets <home>/secrets.shared.sops.json, its part of src/secrets/shared.sops.json
#   - every file is encrypted to exactly its recipients
# A secret of kind dotfiles:<file> is copied from that file of the dotfiles' secrets.
#
# A file is rewritten only when its content or recipients change: sops output is randomized, and rewriting unchanged
# files would churn the public history. A rewrite always encrypts afresh (decrypt, then encrypt under a new data key).
# Rejected: `sops updatekeys`, which re-wraps the file's old data key for the new recipients; whoever held a removed
# admin key splices their key stanza from the public history onto the new file and reads every later value.
# Removing an admin recipient also renews every host key: the removed key opens every age.sops in history, and with
# it every host key of the time, which would go on opening the new files.
#
# Every check runs before the first write, and every write is atomic (sops-encrypt.sh). Writes go: rules, host keys,
# every values file with its new values added, the shared copies, then the removals. A failed run leaves no file
# encrypted to a key that is not stored and no value without a copy, and a rerun converges.
#
# usage: secrets-sync.sh [--apply] [--prune] [--generate-guarded] [--plan <file>] [--host-keys-out <file>]
#   (no flag)           dry run: print what would change
#   --apply             write
#   --prune             delete the values of secrets nothing declares
#   --generate-guarded  generate missing guardsData secrets too: a first deploy (init.sh), or one declared new
#   --plan              the plan as json instead of evaluating the flake (legacyPackages.x86_64-linux.secrets.plan)
#   --host-keys-out     with --apply, also write {"<configuration>": "<its age private key>"} there, mode 0600 (sync.sh)
# env: SOPS_AGE_KEY_FILE         the key that unlocks this run (default secrets/age.txt, the dotfiles key)
#      SECRETS_ADMIN_RECIPIENTS  space separated recipients in place of src/secrets/admins.txt (tests)
#      DOTFILES                  the dotfiles checkout (default ~/projects/arch-dotfiles)
set -euo pipefail

usage() { echo "usage: secrets-sync.sh [--apply] [--prune] [--generate-guarded] [--plan <file>] [--host-keys-out <file>]" >&2; exit 2; }
APPLY=0
PRUNE=0
GENERATE_GUARDED=0
PLAN_IN=""
HOST_KEYS_OUT=""
while [ $# -gt 0 ]; do
  case "$1" in
    --apply) APPLY=1; shift ;;
    --prune) PRUNE=1; shift ;;
    --generate-guarded) GENERATE_GUARDED=1; shift ;;
    --plan) [ $# -ge 2 ] || usage; PLAN_IN=$2; shift 2 ;;
    --host-keys-out) [ $# -ge 2 ] || usage; HOST_KEYS_OUT=$2; shift 2 ;;
    *) usage ;;
  esac
done

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SRC="$ROOT_DIR/src"
SOPS_CONFIG="$ROOT_DIR/.sops.yaml"
ENCRYPT="$SRC/scripts/sops-encrypt.sh"
# ntfy access tokens are tk_ plus this many of [a-z0-9]; any other shape stops ntfy from starting
NTFY_TOKEN_CHARS=29
# garage access key ids are GK plus 12 random bytes in hex
GARAGE_KEY_ID_BYTES=12
# a wireguard private key is 32 bytes; wireguard clamps any 32 bytes into a valid curve25519 scalar
WIREGUARD_KEY_BYTES=32
GUARDED_PREFIX=guardsData:

# shellcheck source=src/scripts/lib/tools.sh
. "$SRC/scripts/lib/tools.sh"
# shellcheck source=src/scripts/lib/secrets.sh
. "$SRC/scripts/lib/secrets.sh"
tools_require sops jq age-keygen openssl
[ -n "$PLAN_IN" ] || tools_require nix

export SOPS_AGE_KEY_FILE="${SOPS_AGE_KEY_FILE:-$ROOT_DIR/secrets/age.txt}"

WORK=$(umask 077; mktemp -d)
trap 'find "$WORK" -type f -exec shred -u {} + 2>/dev/null; rm -rf "$WORK"' EXIT
PLAN="$WORK/plan.json"

join_commas() { local IFS=,; echo "$*"; }
# the sorted age recipients a sops file is encrypted to
recipients_of() { jq -r '.sops.age[]?.recipient' "$1" | sort; }
# canonical plaintext: sorted json, a binary file (age.sops) as it is
canonical() { case "$1" in *.json) jq -S . ;; *) cat ;; esac; }
in_plan() { jq -e --arg f "$1" '.files | has($f)' "$PLAN" >/dev/null; }

# -----------------------------------------------------------------------------
# CHECKS: nothing is written before all of them pass
# -----------------------------------------------------------------------------

secrets_admins_load
secrets_plan_load "$PLAN" "$PLAN_IN"
mapfile -t CONFIGS < <(jq -r '.hosts | keys[]' "$PLAN")

# every values file, declared or on disk: {"<file>": {"<name>": "<value>"}}
mapfile -t VALUE_FILES < <({
  jq -r '.secrets[].file' "$PLAN"
  [ ! -f "$SRC/$SECRETS_CATALOG_FILE" ] || echo "$SECRETS_CATALOG_FILE"
  for dir in "${SECRETS_HOME_DIRS[@]}"; do
    for path in "$SRC/$dir"/*/"$SECRETS_VALUES_NAME"; do [ ! -f "$path" ] || echo "${path#"$SRC/"}"; done
  done
} | sort -u)
echo '{}' > "$WORK/old.json"
for f in "${VALUE_FILES[@]}"; do
  [ -f "$SRC/$f" ] || continue
  sops --decrypt "$SRC/$f" > "$WORK/one.json" || { echo "ERROR: src/$f does not decrypt with $SOPS_AGE_KEY_FILE" >&2; exit 1; }
  jq --arg f "$f" --slurpfile v "$WORK/one.json" '.[$f] = ($v[0] | del(.sops))' "$WORK/old.json" > "$WORK/t" && mv "$WORK/t" "$WORK/old.json"
done

# every host's key: the stored one, or a new one when it has none or an admin recipient it was encrypted to is gone
echo '{}' > "$WORK/keys.json"
declare -A HOST_RECIPIENT=()
for c in "${CONFIGS[@]}"; do
  home=$(jq -r --arg c "$c" '.hosts[$c].home' "$PLAN")
  state=new
  if [ -f "$SRC/$home/$SECRETS_KEY_NAME" ]; then
    key=$(sops --decrypt "$SRC/$home/$SECRETS_KEY_NAME") || { echo "ERROR: src/$home/$SECRETS_KEY_NAME does not decrypt with $SOPS_AGE_KEY_FILE" >&2; exit 1; }
    [ "$(cat "$SRC/$home/$SECRETS_PUB_NAME" 2>/dev/null)" = "$(age-keygen -y <<<"$key")" ] \
      || { echo "ERROR: src/$home/$SECRETS_PUB_NAME is not the public half of its $SECRETS_KEY_NAME" >&2; exit 1; }
    state=kept
    [ -z "$(comm -23 <(recipients_of "$SRC/$home/$SECRETS_KEY_NAME") <(echo "$ADMIN_SORTED"))" ] || state=renewed
  elif [ -e "$SRC/$home/$SECRETS_PUB_NAME" ]; then
    echo "ERROR: src/$home/$SECRETS_PUB_NAME has no $SECRETS_KEY_NAME beside it" >&2; exit 1
  fi
  if [ "$state" != kept ]; then
    key=$(age-keygen 2>/dev/null | grep '^AGE-SECRET-KEY-')
    echo "key     $c: $state"
  fi
  jq --arg c "$c" --arg k "$key" '.[$c] = $k' "$WORK/keys.json" > "$WORK/t" && mv "$WORK/t" "$WORK/keys.json"
  HOST_RECIPIENT[$c]=$(age-keygen -y <<<"$key")
done

# -----------------------------------------------------------------------------
# PLAN: every value where it is declared, every file's plaintext and rule
# -----------------------------------------------------------------------------

# secret_generate <kind>: a fresh value, or nothing for a kind a human fills
secret_generate() {
  local v
  case "${1#"$GUARDED_PREFIX"}" in
    hex:*) openssl rand -hex "${1#*hex:}" ;;
    wireguard) openssl rand -base64 "$WIREGUARD_KEY_BYTES" ;;
    ntfy-token)
      # bounded input: tr reading /dev/urandom dies of SIGPIPE when head closes, and pipefail aborts the script
      v="tk_$(head -c 512 /dev/urandom | LC_ALL=C tr -dc a-z0-9 | cut -c1-"$NTFY_TOKEN_CHARS")"
      [ "${#v}" -eq $((NTFY_TOKEN_CHARS + 3)) ] || { echo "ERROR: could not generate an ntfy token" >&2; exit 1; }
      echo "$v" ;;
    garage-key-id) echo "GK$(openssl rand -hex "$GARAGE_KEY_ID_BYTES")" ;;
    manual|public|dotfiles:*) ;;
    *) echo "ERROR: unknown kind $1" >&2; exit 1 ;;
  esac
}

# each declared secret's value: from its own file, else from any other file holding it (a move), else generated
jq -n --slurpfile old "$WORK/old.json" --slurpfile plan "$PLAN" '
  $old[0] as $o | $plan[0].secrets | with_entries(.key as $k | .value.file as $f | .value =
    if ($o[$f] // {} | has($k)) then {value: $o[$f][$k]}
    else first($o | to_entries[] | select(.value | has($k)) | {value: .value[$k], from: .key}) // null end)' > "$WORK/found.json"
while IFS=$'\t' read -r k from to; do
  echo "move    $k: $from -> $to"
done < <(jq -r --slurpfile plan "$PLAN" 'to_entries[] | select(.value.from) | [.key, .value.from, $plan[0].secrets[.key].file] | @tsv' "$WORK/found.json")
# a fresh value for a guarded secret would lock out whatever the lost one protected
mapfile -t GUARDED_MISSING < <(jq -r --slurpfile plan "$PLAN" --arg g "$GUARDED_PREFIX" 'to_entries[]
  | select(.value == null and ($plan[0].secrets[.key].kind | startswith($g))) | "\(.key) in src/\($plan[0].secrets[.key].file)"' "$WORK/found.json")
if [ "${#GUARDED_MISSING[@]}" -gt 0 ] && [ "$GENERATE_GUARDED" = 0 ]; then
  echo "ERROR: these secrets guard data and have no value; a fresh one would lock the data out:" >&2
  printf '  %s\n' "${GUARDED_MISSING[@]}" >&2
  echo "  Restore each one: sops set src/<file> '[\"<name>\"]' '\"<value>\"'. Only for one that guards nothing yet: --generate-guarded." >&2
  exit 1
fi
while IFS=$'\t' read -r k kind file; do
  v=$(secret_generate "$kind")
  if [ -n "$v" ]; then echo "add     $k -> $file (generated, $kind)"; else echo "add     $k -> $file (empty, fill it: sops src/$file)"; fi
  jq --arg k "$k" --arg v "$v" '.[$k] = {value: $v}' "$WORK/found.json" > "$WORK/t" && mv "$WORK/t" "$WORK/found.json"
done < <(jq -r --slurpfile plan "$PLAN" 'to_entries[] | select(.value == null) | [.key, $plan[0].secrets[.key].kind, $plan[0].secrets[.key].file] | @tsv' "$WORK/found.json")

# kind dotfiles:<file>: the value lives in the dotfiles' secrets; the lab's copy follows it on every run
while IFS=$'\t' read -r k kind file; do
  source_file="$SECRETS_DOTFILES_DIR/${kind#dotfiles:}"
  if ! grep -qs '^AGE-SECRET-KEY-' "$SECRETS_DOTFILES_DIR/age.txt"; then
    echo "skip    $k: dotfiles secrets locked or absent, value kept"
  elif [ ! -s "$source_file" ]; then
    echo "missing $k: put it in $source_file, then re-run"
  elif [ "$(jq -r --arg k "$k" '.[$k].value // ""' "$WORK/found.json")" != "$(<"$source_file")" ]; then
    echo "copy    $k <- dotfiles ${kind#dotfiles:} -> $file"
    jq --arg k "$k" --rawfile v "$source_file" '.[$k] = {value: ($v | rtrimstr("\n"))}' "$WORK/found.json" > "$WORK/t" \
      && mv "$WORK/t" "$WORK/found.json"
  fi
done < <(jq -r '.secrets | to_entries[] | select(.value.kind | startswith("dotfiles:")) | [.key, .value.kind, .value.file] | @tsv' "$PLAN")

while IFS=$'\t' read -r k file; do
  if [ "$PRUNE" = 1 ]; then echo "remove  $k from $file (nothing declares it)"; else echo "unused  $k in $file (nothing declares it; --prune deletes it)"; fi
done < <(jq -r --slurpfile plan "$PLAN" 'to_entries[] | .key as $f | .value | keys[] | select(. as $k | $plan[0].secrets | has($k) | not) | [., $f] | @tsv' "$WORK/old.json")

# the values every file ends with: declared ones where they are declared, undeclared ones kept unless pruned
jq -n --slurpfile old "$WORK/old.json" --slurpfile plan "$PLAN" --slurpfile found "$WORK/found.json" --argjson prune "$PRUNE" '
  $plan[0].secrets as $s
  | ($old[0] | map_values(with_entries(select(.key as $k | ($s | has($k) | not) and $prune == 0))))
  | reduce ($s | to_entries[]) as $e (.; .[$e.value.file][$e.key] = $found[0][$e.key].value)' > "$WORK/new.json"

# plaintext/<file>: every file's content; age.sops the bare key
mkdir -p "$WORK/plain"
plain_put() { mkdir -p "$WORK/plain/$(dirname "$1")"; cat > "$WORK/plain/$1"; }
for c in "${CONFIGS[@]}"; do
  home=$(jq -r --arg c "$c" '.hosts[$c].home' "$PLAN")
  jq -r --arg c "$c" '.[$c]' "$WORK/keys.json" | plain_put "$home/$SECRETS_KEY_NAME"
  if in_plan "$home/$SECRETS_SHARED_NAME"; then
    jq -S --arg c "$c" --arg cat "$SECRETS_CATALOG_FILE" --slurpfile plan "$PLAN" \
      '.[$cat] as $v | $plan[0].hosts[$c].shared | map({key: ., value: $v[.]}) | from_entries' "$WORK/new.json" | plain_put "$home/$SECRETS_SHARED_NAME"
  fi
done
mapfile -t VALUE_FILES < <(jq -r 'keys[]' "$WORK/new.json")

{
  cat <<EOF
# generated by src/scripts/secrets-sync.sh from modules/secrets.nix, src/secrets/admins.txt and every age.pub
#
# Every file is encrypted to the admins and the hosts that read it: <home>/age.sops to the admins only,
# <home>/secrets.sops.json and secrets.shared.sops.json to its host, an app's secrets.sops.json to its readers.
creation_rules:
EOF
  while IFS=$'\t' read -r file readers; do
    recipients=("${ADMIN_RECIPIENTS[@]}")
    for c in $readers; do recipients+=("${HOST_RECIPIENT[$c]}"); done
    printf '  - path_regex: src/%s$\n    age: %s\n' "${file//./\\.}" "$(join_commas "${recipients[@]}")"
  done < <(jq -r '.files | to_entries[] | [.key, (.value | join(" "))] | @tsv' "$PLAN")
} > "$WORK/sops.yaml"

# -----------------------------------------------------------------------------
# WRITE: rules, keys, values with additions, shared copies, removals (a dry run only reports)
# -----------------------------------------------------------------------------
changed=0

# write_file <file> <plaintext>: encrypted to the admins and the file's readers, when its content or recipients differ
write_file() {
  local file=$1 plain=$2 want c
  want=$(for c in $(jq -r --arg f "$file" '.files[$f] // [] | .[]' "$PLAN"); do echo "${HOST_RECIPIENT[$c]}"; done
    printf '%s\n' "${ADMIN_RECIPIENTS[@]}")
  want=$(sort <<<"$want")
  if [ -f "$SRC/$file" ] && [ "$(recipients_of "$SRC/$file")" = "$want" ] \
     && cmp -s <(canonical "$file" < "$plain") <(sops --decrypt "$SRC/$file" 2>/dev/null | canonical "$file" 2>/dev/null); then
    return 0
  fi
  echo "write   src/$file"
  changed=$((changed + 1))
  [ "$APPLY" = 1 ] || return 0
  mkdir -p "$SRC/$(dirname "$file")"
  "$ENCRYPT" "$SRC/$file" < "$plain"
}
# remove_file <file>: a file the plan no longer has
remove_file() {
  [ -e "$SRC/$1" ] || return 0
  echo "delete  src/$1"
  changed=$((changed + 1))
  [ "$APPLY" = 0 ] || rm -f "$SRC/$1"
}

if ! cmp -s "$WORK/sops.yaml" "$SOPS_CONFIG"; then
  echo "write   .sops.yaml"
  changed=$((changed + 1))
  [ "$APPLY" = 0 ] || cp "$WORK/sops.yaml" "$SOPS_CONFIG"
fi

for c in "${CONFIGS[@]}"; do
  home=$(jq -r --arg c "$c" '.hosts[$c].home' "$PLAN")
  write_file "$home/$SECRETS_KEY_NAME" "$WORK/plain/$home/$SECRETS_KEY_NAME"
  if [ "$(cat "$SRC/$home/$SECRETS_PUB_NAME" 2>/dev/null)" != "${HOST_RECIPIENT[$c]}" ]; then
    echo "write   src/$home/$SECRETS_PUB_NAME"
    [ "$APPLY" = 0 ] || echo "${HOST_RECIPIENT[$c]}" > "$SRC/$home/$SECRETS_PUB_NAME"
  fi
done

# first every value in its new place beside its old copies, then the copies go: no failure point loses one
if [ "$APPLY" = 1 ]; then
  for f in "${VALUE_FILES[@]}"; do
    jq -n --slurpfile old "$WORK/old.json" --slurpfile new "$WORK/new.json" --arg f "$f" '($old[0][$f] // {}) + $new[0][$f]' \
      | plain_put "union/$f"
    write_file "$f" "$WORK/plain/union/$f"
  done
fi
for c in "${CONFIGS[@]}"; do
  home=$(jq -r --arg c "$c" '.hosts[$c].home' "$PLAN")
  [ ! -f "$WORK/plain/$home/$SECRETS_SHARED_NAME" ] || write_file "$home/$SECRETS_SHARED_NAME" "$WORK/plain/$home/$SECRETS_SHARED_NAME"
done
for f in "${VALUE_FILES[@]}"; do
  if [ "$(jq --arg f "$f" '.[$f] | length' "$WORK/new.json")" = 0 ] && ! in_plan "$f"; then remove_file "$f"; continue; fi
  jq --arg f "$f" '.[$f]' "$WORK/new.json" | plain_put "$f"
  write_file "$f" "$WORK/plain/$f"
done

# keys and shared copies of hosts that are gone, or that read no shared secret any more
for dir in "${SECRETS_HOME_DIRS[@]}"; do
  for path in "$SRC/$dir"/*/"$SECRETS_KEY_NAME" "$SRC/$dir"/*/"$SECRETS_SHARED_NAME"; do
    [ -e "$path" ] || continue
    file=${path#"$SRC/"}
    in_plan "$file" && continue
    remove_file "$file"
    [ "$(basename "$file")" != "$SECRETS_KEY_NAME" ] || remove_file "$(dirname "$file")/$SECRETS_PUB_NAME"
  done
done
if [ "$APPLY" = 1 ] && [ -d "$SRC/generated/nodes" ]; then find "$SRC/generated/nodes" -mindepth 1 -maxdepth 1 -type d -empty -delete; fi

if [ -n "$HOST_KEYS_OUT" ] && [ "$APPLY" = 1 ]; then
  (umask 077; cp "$WORK/keys.json" "$HOST_KEYS_OUT")
fi

if [ "$APPLY" = 0 ] && [ "$changed" -gt 0 ]; then
  echo "dry run: $changed file(s) would change. Re-run with --apply to write (add --prune to delete unused values)."
else
  echo ">>> Secrets: ${#CONFIGS[@]} hosts, $changed file(s) changed."
fi
