#!/usr/bin/env bash
# one age key per host: each host decrypts only src/host-secrets/<host>.json, the secrets its own config reads
#
# src/secrets.json stays the single file a human edits (sops src/secrets.json). This script derives from it:
#   src/host-keys.json            every host's age private key, encrypted to the admin keys only, never deployed
#   src/host-secrets/<host>.json  the subset a host uses, encrypted to the admin keys and that host's key
#   .sops.yaml                    the creation rules for all of the above
# sync.sh runs it before every build and hands each host only its own key, so root on one guest no longer
# decrypts every other guest's secrets. A file is rewritten only when its content or recipients change: sops
# output is randomized, and rewriting unchanged files would churn the public history.
#
# usage: secrets-hosts.sh [--host-keys-out <file>]
#   --host-keys-out  also write {"<nixos configuration>": "<its age private key>"} there, mode 0600, for sync.sh
set -euo pipefail

HOST_KEYS_OUT=""
while [ $# -gt 0 ]; do
  case "$1" in
    --host-keys-out) HOST_KEYS_OUT=${2:?--host-keys-out needs a file}; shift 2 ;;
    *) echo "usage: secrets-hosts.sh [--host-keys-out <file>]" >&2; exit 2 ;;
  esac
done

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SRC="$ROOT_DIR/src"
SECRETS="$SRC/secrets.json"
HOST_KEYS="$SRC/host-keys.json"
HOST_DIR="$SRC/host-secrets"
SOPS_CONFIG="$ROOT_DIR/.sops.yaml"
ENCRYPT="$SRC/scripts/sops-encrypt.sh"

# the owner's dotfiles key and YubiKey: they open every file, nothing else opens the admin-only ones
ADMIN_RECIPIENTS=(
  age1ws68kvrg7fxxw8epnv8xc8pas2va5j8qchsjfpsns3zle0p0uq6qe9r609
  age1yubikey1qtpq7nvpdtnktqu0yerz30q75ee4tm685my3jtag0vgzp5jgees9qn9my80
)

export SOPS_AGE_KEY_FILE="${SOPS_AGE_KEY_FILE:-$ROOT_DIR/secrets/age.txt}"
for tool in sops jq age-keygen nix; do
  command -v "$tool" >/dev/null || { echo "ERROR: $tool not installed."; exit 1; }
done
grep -qs '^AGE-SECRET-KEY-' "$SOPS_AGE_KEY_FILE" || { echo "ERROR: admin age key not readable at $SOPS_AGE_KEY_FILE"; exit 1; }

WORK=$(umask 077; mktemp -d)
trap 'rm -rf "$WORK"' EXIT

join_commas() { local IFS=,; echo "$*"; }

# -----------------------------------------------------------------------------
# what every host reads: {"<hostName>": ["secret", ...]}
# sopsFile stays unforced: it points into host-secrets/, which this run may be about to create
# -----------------------------------------------------------------------------
echo ">>> Secrets: evaluating which host reads which secret..."
nix eval --json --extra-experimental-features "nix-command flakes" "$SRC#nixosConfigurations" --apply '
  builtins.mapAttrs (_: c: {
    host = c.config.networking.hostName;
    keys = builtins.sort builtins.lessThan
      (c.pkgs.lib.unique (map (s: s.key) (builtins.attrValues c.config.sops.secrets)));
  })' > "$WORK/configs.json"
jq 'with_entries({key: .value.host, value: .value.keys})' "$WORK/configs.json" > "$WORK/wanted.json"
dupes=$(jq -r '[.[].host] | group_by(.) | map(select(length > 1) | .[0]) | .[]' "$WORK/configs.json")
[ -z "$dupes" ] || { echo "ERROR: hostnames shared by several configurations, one key cannot serve them: $dupes"; exit 1; }

sops --decrypt "$SECRETS" | jq 'del(.sops)' > "$WORK/secrets.json"

missing=$(jq -r --slurpfile have "$WORK/secrets.json" '
  [to_entries[] | .key as $h | .value[] | select($have[0][.] == null) | "\($h): \(.)"] | .[]' "$WORK/wanted.json")
[ -z "$missing" ] || { echo "ERROR: configs read secrets missing from src/secrets.json (run src/scripts/secrets-sync.sh):"; echo "$missing"; exit 1; }

# -----------------------------------------------------------------------------
# host keys: create the missing ones, drop the ones of hosts that are gone
# -----------------------------------------------------------------------------
if [ -f "$HOST_KEYS" ]; then sops --decrypt "$HOST_KEYS" | jq 'del(.sops)' > "$WORK/keys.json"; else echo '{}' > "$WORK/keys.json"; fi
cp "$WORK/keys.json" "$WORK/keys.old.json"
for host in $(jq -r 'keys[]' "$WORK/wanted.json"); do
  if [ "$(jq -r --arg h "$host" '.[$h] // empty' "$WORK/keys.json")" = "" ]; then
    key=$(age-keygen 2>/dev/null | grep '^AGE-SECRET-KEY-')
    jq --arg h "$host" --arg k "$key" '.[$h] = $k' "$WORK/keys.json" > "$WORK/keys.t" && mv "$WORK/keys.t" "$WORK/keys.json"
    echo "    new key for $host"
  fi
done
jq --slurpfile want "$WORK/wanted.json" 'with_entries(select(.key as $h | $want[0] | has($h)))' "$WORK/keys.json" \
  > "$WORK/keys.t" && mv "$WORK/keys.t" "$WORK/keys.json"

host_recipient() { jq -r --arg h "$1" '.[$h]' "$WORK/keys.json" | age-keygen -y; }

# -----------------------------------------------------------------------------
# .sops.yaml: the admin-only files, then one rule per host
# -----------------------------------------------------------------------------
{
  cat <<EOF
# generated by src/scripts/secrets-hosts.sh, edit that script instead
#
# src/secrets.json is the source of truth (sops src/secrets.json). Every host gets its own age key and
# src/host-secrets/<host>.json, holding only the secrets its config reads, encrypted to it and the admin keys.
creation_rules:
  - path_regex: src/secrets\.json$
    age: $(join_commas "${ADMIN_RECIPIENTS[@]}")
  - path_regex: src/terraform\.tfvars\.sops\.json$
    age: $(join_commas "${ADMIN_RECIPIENTS[@]}")
  - path_regex: src/host-keys\.json$
    age: $(join_commas "${ADMIN_RECIPIENTS[@]}")
EOF
  for host in $(jq -r 'keys[]' "$WORK/wanted.json"); do
    printf '  - path_regex: src/host-secrets/%s\\.json$\n    age: %s\n' \
      "${host//./\\.}" "$(join_commas "${ADMIN_RECIPIENTS[@]}" "$(host_recipient "$host")")"
  done
} > "$WORK/sops.yaml"
if ! cmp -s "$WORK/sops.yaml" "$SOPS_CONFIG"; then
  cp "$WORK/sops.yaml" "$SOPS_CONFIG"
  echo "    .sops.yaml updated"
fi

# admin-only and nothing else changed: keep the ciphertext, so git sees no change
if [ ! -f "$HOST_KEYS" ] || ! cmp -s <(jq -S . "$WORK/keys.json") <(jq -S . "$WORK/keys.old.json"); then
  jq -S . "$WORK/keys.json" | "$ENCRYPT" "$HOST_KEYS"
  echo "    src/host-keys.json updated"
fi

# rotating the admin key is editing ADMIN_RECIPIENTS: the admin-only files follow here, the host files below
want_admin=$(printf '%s\n' "${ADMIN_RECIPIENTS[@]}" | sort)
for file in "$SECRETS" "$SRC/terraform.tfvars.sops.json" "$HOST_KEYS"; do
  [ -f "$file" ] || continue
  if [ "$(jq -r '.sops.age[].recipient' "$file" | sort)" != "$want_admin" ]; then
    (cd "$ROOT_DIR" && sops updatekeys --yes "$file" >/dev/null)
    echo "    $(basename "$file") re-keyed to the admin recipients"
  fi
done

# -----------------------------------------------------------------------------
# per-host files
# -----------------------------------------------------------------------------
mkdir -p "$HOST_DIR"
changed=0
for host in $(jq -r 'keys[]' "$WORK/wanted.json"); do
  file="$HOST_DIR/$host.json"
  jq -S --arg h "$host" --slurpfile want "$WORK/wanted.json" \
    'with_entries(select(.key as $k | $want[0][$h] | index($k)))' "$WORK/secrets.json" > "$WORK/host.json"
  want_recipients=$(printf '%s\n' "${ADMIN_RECIPIENTS[@]}" "$(host_recipient "$host")" | sort)
  if [ -f "$file" ] \
    && cmp -s "$WORK/host.json" <(sops --decrypt "$file" | jq -S 'del(.sops)') \
    && [ "$(jq -r '.sops.age[].recipient' "$file" | sort)" = "$want_recipients" ]; then
    continue
  fi
  "$ENCRYPT" "$file" < "$WORK/host.json"
  echo "    src/host-secrets/$host.json updated ($(jq length "$WORK/host.json") secrets)"
  changed=$((changed + 1))
done

# a host that is gone keeps no ciphertext of secrets that may still be live elsewhere
for file in "$HOST_DIR"/*.json; do
  [ -e "$file" ] || continue
  host=$(basename "$file" .json)
  jq -e --arg h "$host" 'has($h)' "$WORK/wanted.json" >/dev/null || { rm -f "$file"; echo "    removed $file"; }
done

if [ -n "$HOST_KEYS_OUT" ]; then
  (umask 077; jq --slurpfile keys "$WORK/keys.json" 'map_values($keys[0][.host])' "$WORK/configs.json" > "$HOST_KEYS_OUT")
fi

echo ">>> Secrets: $(jq length "$WORK/wanted.json") hosts, $changed host file(s) rewritten."
